blank_issues_enabled: false
contact_links:
  - name: Sonar Community
    url: https://community.sonarsource.com/
    about: Ask and answer questions under the relevant product here. You can also submit suggestions of improvement or bugs in the community.
  - name: Sonar NPM Scanner Jira Project
    url: https://sonarsource.atlassian.net/browse/SCANNPM/
    about: Browse existing issues here.
